root: true
ignorePatterns:
  - node_modules/**/*
parserOptions:
  project:
    - tsconfig.json
  createDefaultProgram: true
extends:
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
  - plugin:import/recommended
  - plugin:import/typescript
rules:
  prettier/prettier:
    - error
    - printWidth: 120
      endOfLine: auto
  import/order:
    - error
    - newlines-between: always
      alphabetize:
        order: asc
  "@typescript-eslint/no-empty-function":
    - warn
  "@typescript-eslint/no-unused-vars":
    - warn
    - args: after-used
      argsIgnorePattern: "^_"
      varsIgnorePattern: "^_"
  "@typescript-eslint/naming-convention":
    - warn
    - selector: variable
      leadingUnderscore: allow
      format:
        - camelCase
        - UPPER_CASE
